// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtmFLpnF0-vOl1ZSA90hbqchzXNUiPuh0',
    appId: '1:623970889745:android:46081083cfce4ed8cf81b0',
    messagingSenderId: '623970889745',
    projectId: 'stichanda-1cacd',
    storageBucket: 'stichanda-1cacd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7zuOi5hS2qLc-96Zd1i6cfxMUH4WrPCg',
    appId: '1:623970889745:ios:bfd8d9cc262de804cf81b0',
    messagingSenderId: '623970889745',
    projectId: 'stichanda-1cacd',
    storageBucket: 'stichanda-1cacd.firebasestorage.app',
    iosBundleId: 'com.example.stichandaDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7zuOi5hS2qLc-96Zd1i6cfxMUH4WrPCg',
    appId: '1:623970889745:ios:bfd8d9cc262de804cf81b0',
    messagingSenderId: '623970889745',
    projectId: 'stichanda-1cacd',
    storageBucket: 'stichanda-1cacd.firebasestorage.app',
    iosBundleId: 'com.example.stichandaDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdSugjW6Zse19FgKRq_taeiBMVLHy3KHw',
    appId: '1:623970889745:web:92069025a2cf607bcf81b0',
    messagingSenderId: '623970889745',
    projectId: 'stichanda-1cacd',
    authDomain: 'stichanda-1cacd.firebaseapp.com',
    storageBucket: 'stichanda-1cacd.firebasestorage.app',
    measurementId: 'G-6J6WEQGHFM',
  );
}
