import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_stripe/flutter_stripe.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import 'theme/light_theme.dart';
import 'controller/auth_cubit.dart';
import 'controller/order_cubit.dart';
import 'controller/tailor_cubit.dart';
import 'controller/payment_cubit.dart';
import 'controller/rider_cubit.dart';
import 'modules/chat/cubit/chat_cubit.dart';
import 'data/repository/auth_repository.dart';
import 'data/repository/order_repository.dart';
import 'data/repository/rider_repository.dart';
import 'data/payment/payment_service.dart';
import 'data/repository/tailor_repository.dart';
import 'modules/chat/repository/chat_repository.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`
import 'view/screen/splash_screen.dart';
import 'stripe_config.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Initialize Stripe publishable key (test mode)
  Stripe.publishableKey = StripeConfig.publishableKey;
  await Stripe.instance.applySettings();

  // Initialize Supabase (required for image uploads)

    await Supabase.initialize(
      url: 'https://rzkrwgexdqksrudynxvp.supabase.co',
      anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6a3J3Z2V4ZHFrc3J1ZHlueHZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3MTUxNjAsImV4cCI6MjA3NzI5MTE2MH0.bQytv6utSf9ArstDr6nu1K5L66XuFj5vTBYiWSR-xRw',
    );


  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    // Initialize repositories
    final authRepository = AuthRepository();
    final orderRepository = OrderRepository();
    final tailorRepository = TailorRepository();
    final riderRepository = RiderRepository();
    final paymentService = PaymentService();
    final chatRepository = ChatRepository();

    return MultiRepositoryProvider(
      providers: [
        RepositoryProvider(create: (context) => authRepository),
        RepositoryProvider(create: (context) => orderRepository),
        RepositoryProvider(create: (context) => riderRepository),
      ],
      child: MultiBlocProvider(
        providers: [
          BlocProvider(
            create: (context) => AuthCubit(authRepository),
          ),
          BlocProvider(
            create: (context) => OrderCubit(orderRepository),
          ),
          BlocProvider(
            create: (context) => TailorCubit(),
          ),
          BlocProvider(
            create: (context) => PaymentCubit(paymentService, tailorRepository),
          ),
          BlocProvider(
            create: (context) => RiderCubit(riderRepository),
          ),
          BlocProvider(
            create: (context) => ChatCubit(chatRepository),
          ),
        ],
        child: MaterialApp(
          title: 'Stitchanda',
          debugShowCheckedModeBanner: false,
          theme: lightTheme,
          home: const SplashScreen(),
        ),
      ),
    );
  }
}